-- ============================================================
-- Fase 40: Seed corpus documental — Leyes fiscales España
-- ============================================================

-- 1. norma — leyes fiscales principales
INSERT INTO norma (codigo, titulo, boe_id, eli_uri, jurisdiccion, tipo_fuente, tipo_documento, ambito, estado_cobertura, vigente_desde) VALUES
  ('LGT', 'Ley 58/2003, General Tributaria', 'BOE-A-2003-21814', 'https://www.eli.es/es/l/2003/12/17/58', 'es', 'ley organica', 'ley', 'tributario', 'vigente', '2003-12-17'),
  ('LIRPF', 'Ley 35/2006, IRPF', 'BOE-A-2006-22265', 'https://www.eli.es/es/l/2006/12/28/35', 'es', 'ley', 'ley', 'tributario', 'vigente', '2006-12-28'),
  ('LIVA', 'Ley 37/1992, IVA', 'BOE-A-1992-27212', 'https://www.eli.es/es/l/1992/12/28/37', 'es', 'ley', 'ley', 'tributario', 'vigente', '1992-12-28'),
  ('LGT-REG', 'RGL (RD 439/2000)', 'BOE-A-2000-18976', 'https://www.eli.es/es/rd/2000/03/24/439', 'es', 'real decreto', 'reglamento', 'tributario', 'vigente', '2000-03-24'),
  ('LIS', 'Ley 27/2014, IS', 'BOE-A-2014-10399', 'https://www.eli.es/es/l/2014/11/20/27', 'es', 'ley', 'ley', 'tributario', 'vigente', '2014-11-20'),
  ('LGC', 'Ley 58/2003, General Tributaria (reglamento)', 'BOE-A-2003-21814', 'https://www.eli.es/es/l/2003/12/17/58', 'es', 'ley', 'ley', 'tributario', 'vigente', '2003-12-17');

-- 2. articulo — artículos de las leyes fiscales
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '1', 'Ámbito de aplicación', 'articulo', 'b078f69b5d32d65ea4c5f466a60a49a9' FROM norma n WHERE n.codigo = 'LGT';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '2', 'Principios de ejecución tributaria', 'articulo', '16941967babcc2a63c05cdd1a899d8d3' FROM norma n WHERE n.codigo = 'LGT';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '3', 'Interpretación tributaria', 'articulo', '659dfd352dfd3531bae04af0bb5ec5ba' FROM norma n WHERE n.codigo = 'LGT';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '4', 'Derechos de la Administración', 'articulo', '5aaefbd99ab365de802dfa82d1631c0a' FROM norma n WHERE n.codigo = 'LGT';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '5', 'Obligaciones tributarias', 'articulo', '608a4968731bee198d857392dc21df1c' FROM norma n WHERE n.codigo = 'LGT';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '6', 'Obligación tributaria principal: prestación patrimonial', 'articulo', '3d2f59a149ddf0e0a2f2c4b5af9b9faa' FROM norma n WHERE n.codigo = 'LGT';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '7', 'Obligaciones tributarias accesorias', 'articulo', '0ea31c64e0c7f240d53555946a7f2526' FROM norma n WHERE n.codigo = 'LGT';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '8', 'Obligaciones formales genéricas', 'articulo', 'a3676a600bdf521f831d07f1cdded08d' FROM norma n WHERE n.codigo = 'LGT';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '9', 'Obligaciones derivadas', 'articulo', 'a0f12ffd8dfef67e63f7ce1ec7e00a39' FROM norma n WHERE n.codigo = 'LGT';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '10', 'Sujeto pasivo', 'articulo', 'dfe2cffa17884632c7d48e573b34f7a7' FROM norma n WHERE n.codigo = 'LGT';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '11', 'Solidaridad y responsabilidad', 'articulo', '729ba597e5d9e6fe9308da6b8b635bfa' FROM norma n WHERE n.codigo = 'LGT';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '12', 'Hecho imponible', 'articulo', 'dc81664e8d783e0e14e1602fe0ec3c15' FROM norma n WHERE n.codigo = 'LGT';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '13', 'Fuentes del derecho tributario', 'articulo', '69cee6d014fc157d6e2a9dccb8ff4d5a' FROM norma n WHERE n.codigo = 'LGT';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '14', 'Normas sobre la obligación tributar', 'articulo', 'cd3425317933eac60c645d1bf7da0017' FROM norma n WHERE n.codigo = 'LGT';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '15', 'Recargo voluntario e involuntario', 'articulo', 'c17ab09bfe3393bf1a6efd15ee9bef15' FROM norma n WHERE n.codigo = 'LGT';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '16', 'Plazo de presentación y abono', 'articulo', 'c05b768c75f2aec20f9d726fea05d50c' FROM norma n WHERE n.codigo = 'LGT';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '17', 'Liquidación', 'articulo', '2f050d830ea8c30ebd9d1714eef393a4' FROM norma n WHERE n.codigo = 'LGT';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '18', 'Liquidación de oficio', 'articulo', '66b203a907c5ea3548602bdb0a35081c' FROM norma n WHERE n.codigo = 'LGT';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '19', 'Recaudación', 'articulo', 'b9905d0bdf4e1fb7fd8ecba3234ea6c9' FROM norma n WHERE n.codigo = 'LGT';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '20', 'Período de liquidación', 'articulo', '82439678351e2c75016e6b0845f90f49' FROM norma n WHERE n.codigo = 'LGT';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '21', 'Prescripción', 'articulo', '9618c2991fdd9a5e3fcb4bc224d943c9' FROM norma n WHERE n.codigo = 'LGT';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '22', 'Interrupción', 'articulo', 'b42572f4484b707e876fbef17ee08616' FROM norma n WHERE n.codigo = 'LGT';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '23', 'Reclamación económico-tributaria', 'articulo', '3e677b4a17b8bef05c0a78314288a733' FROM norma n WHERE n.codigo = 'LGT';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '24', 'Inspección de los tributos', 'articulo', '6edab42118c41bf3d1c59b31ac887844' FROM norma n WHERE n.codigo = 'LGT';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '25', 'Prueba', 'articulo', '716b1cc029bd8b25169fb40d137aaffb' FROM norma n WHERE n.codigo = 'LGT';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '26', 'Sanciones', 'articulo', 'e5326f7b8b45ca56a067469bf8796d8c' FROM norma n WHERE n.codigo = 'LGT';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '27', 'Clasificación de infracciones', 'articulo', 'b910f37f513363e953ab340b34f39db7' FROM norma n WHERE n.codigo = 'LGT';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '28', 'Proporcionalidad de las sanciones', 'articulo', '71dd3d56a6f34531deed29679506495c' FROM norma n WHERE n.codigo = 'LGT';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '29', 'Prescripción de las infracciones', 'articulo', 'c042396badc2128592822b30b01d316d' FROM norma n WHERE n.codigo = 'LGT';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '30', 'Responsabilidad', 'articulo', '257b27ffd9f7cc03db4e32c73b307d92' FROM norma n WHERE n.codigo = 'LGT';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '1', 'Ámbito territorial', 'articulo', 'd651bfd8f61505235b6815f130673033' FROM norma n WHERE n.codigo = 'LIRPF';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '2', 'Sujetos pasivos', 'articulo', '7df82638f057aa65b521944791e0f0b7' FROM norma n WHERE n.codigo = 'LIRPF';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '3', 'Rendimientos del trabajo', 'articulo', '44274bad9babd6ba14c75f4ddedfa972' FROM norma n WHERE n.codigo = 'LIRPF';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '4', 'Rendimientos por actividad económica', 'articulo', 'f20fe143d4a31735a071798a097f180d' FROM norma n WHERE n.codigo = 'LIRPF';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '5', 'Rendimientos del capital mobiliario', 'articulo', '88ab7821162bb3e50013961da3c72c8d' FROM norma n WHERE n.codigo = 'LIRPF';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '6', 'Ganancias y pérdidas patrimoniales', 'articulo', '8e58f6544079c73ec4c2afb9f34c0124' FROM norma n WHERE n.codigo = 'LIRPF';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '7', 'Integración en base imponible', 'articulo', '46adfe07e4c2d925fb42a9eaface8d27' FROM norma n WHERE n.codigo = 'LIRPF';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '8', 'Deducciones en la cuota', 'articulo', 'd4293884162ba4cd8e535e4edc465d1f' FROM norma n WHERE n.codigo = 'LIRPF';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '9', 'Deducciones estatales autonómicas', 'articulo', '81b3eb4863fbb002317d981dc03f484d' FROM norma n WHERE n.codigo = 'LIRPF';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '10', 'Retenciones e ingresos a cuenta', 'articulo', 'a373196a4d12927ebcb7865566b34b2f' FROM norma n WHERE n.codigo = 'LIRPF';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '11', 'Mínimo por trabajo realizado', 'articulo', '57ce1f4770016f20869b71809c7eb269' FROM norma n WHERE n.codigo = 'LIRPF';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '12', 'Mínimo por ascendientes y descendientes', 'articulo', '835083c204c3a4ab35de9b597a5827bb' FROM norma n WHERE n.codigo = 'LIRPF';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '13', 'Mínimo por maternidad', 'articulo', 'a188d8315c4b1914e8135dc638814675' FROM norma n WHERE n.codigo = 'LIRPF';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '14', 'Mínimo por situaciones de dependencia', 'articulo', 'a881100d4060ff0f9dac5ea923da0885' FROM norma n WHERE n.codigo = 'LIRPF';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '15', 'Mínimo por inversiones en vivienda habitual', 'articulo', '283d79b97eea7158e7010192386fe84a' FROM norma n WHERE n.codigo = 'LIRPF';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '16', 'Declaración anual', 'articulo', 'e58517bd0887237e8fef3b7c02252799' FROM norma n WHERE n.codigo = 'LIRPF';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '17', 'Forma de presentación', 'articulo', 'bf206a65a25aa373b7e19f55df487138' FROM norma n WHERE n.codigo = 'LIRPF';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '18', 'Plazo de presentación', 'articulo', '8c74cf538e2878e06e479eb93e7ec748' FROM norma n WHERE n.codigo = 'LIRPF';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '19', 'Pagos fraccionados', 'articulo', '2e8870ee9adf22153566dfd6f47bc806' FROM norma n WHERE n.codigo = 'LIRPF';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '20', 'Estadísticas', 'articulo', '1a8748b6a3dedd85229dfb530dfff3f1' FROM norma n WHERE n.codigo = 'LIRPF';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '1', 'Hecho imponible', 'articulo', '83dfd468ed217328b64e4324cc0855f7' FROM norma n WHERE n.codigo = 'LIVA';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '2', 'Sujeto pasivo', 'articulo', '7672a99eb62fa3aeb1ac378ae1e6a056' FROM norma n WHERE n.codigo = 'LIVA';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '3', 'Bienes y servicios', 'articulo', 'b7817c259ccd43fb77fb8bc640e0f0fb' FROM norma n WHERE n.codigo = 'LIVA';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '4', 'Operaciones intracomunitarias', 'articulo', '99cc00d32d1b09e81b665b0e28b927af' FROM norma n WHERE n.codigo = 'LIVA';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '5', 'Entregas y prestaciones de servicios', 'articulo', 'e078b9a867f547edcd5c008ff8891fef' FROM norma n WHERE n.codigo = 'LIVA';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '6', 'Exenciones', 'articulo', '6922bcb5708bf1f927a8a58e31adba67' FROM norma n WHERE n.codigo = 'LIVA';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '7', 'No sujetas', 'articulo', '523e224278f7af0d39b5a9c1c34924ef' FROM norma n WHERE n.codigo = 'LIVA';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '8', 'Tipo de gravamen', 'articulo', '230f87824ffb591861d7e34926732739' FROM norma n WHERE n.codigo = 'LIVA';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '9', 'Devengo', 'articulo', '4309a39f01e408cfaf9e3c257ad27d65' FROM norma n WHERE n.codigo = 'LIVA';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '10', 'Cuota soportada', 'articulo', '552fb281b05ec910da225ac22bf733d5' FROM norma n WHERE n.codigo = 'LIVA';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '11', 'Cuota repercutida', 'articulo', '68305c7aee20cb2478845f163377e579' FROM norma n WHERE n.codigo = 'LIVA';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '12', 'Autoliquidaciones', 'articulo', '9b4417870140ff4006aab19221fbf939' FROM norma n WHERE n.codigo = 'LIVA';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '13', 'Devoluciones', 'articulo', 'd5624091619ccbc6fa77eaa0d70b18d4' FROM norma n WHERE n.codigo = 'LIVA';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '14', 'Libros registro', 'articulo', 'bb9e0e3eb62d6c3c76cfd8077ab2e7c5' FROM norma n WHERE n.codigo = 'LIVA';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '15', 'Facturación', 'articulo', '0677e5b3d3225878568153374a927ae9' FROM norma n WHERE n.codigo = 'LIVA';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '1', 'Ámbito de aplicación', 'articulo', 'a5a1d0dc6992fe0b30f26609da4ef76b' FROM norma n WHERE n.codigo = 'LIS';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '2', 'Sujetos pasivos', 'articulo', 'b11714e452bbba3509c56839b98ebe91' FROM norma n WHERE n.codigo = 'LIS';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '3', 'Base imponible', 'articulo', '67b79a702c39b78f72449010b5134d37' FROM norma n WHERE n.codigo = 'LIS';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '4', 'Rendimientos del capital mobiliario', 'articulo', '42cd61189ae06811e5f7f2b2311e22e6' FROM norma n WHERE n.codigo = 'LIS';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '5', 'Deducciones', 'articulo', '72d2b92fcf71339915428cb0bc5d724b' FROM norma n WHERE n.codigo = 'LIS';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '6', 'Gravamen', 'articulo', '3a42a88a2960999bce6800399068696f' FROM norma n WHERE n.codigo = 'LIS';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '7', 'Devolución', 'articulo', 'bb8e1df09f5fac4ae38f27ba118f4f54' FROM norma n WHERE n.codigo = 'LIS';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '8', 'Plazo de presentación', 'articulo', '96480c3f9ed86431b3420a3510e6eb3e' FROM norma n WHERE n.codigo = 'LIS';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '9', 'Dividendos', 'articulo', 'c7c35ab3397aa250e57d3c08ada30359' FROM norma n WHERE n.codigo = 'LIS';
INSERT INTO articulo (norma_id, numero, titulo, tipo, content_hash) SELECT n.id, '10', 'Deducción por doble tributación internacional', 'articulo', 'ec6abb947bf84a7d1e158bbdd33a7ef3' FROM norma n WHERE n.codigo = 'LIS';

-- 3. version_articulo — versiones de artículos (vigentes)
INSERT INTO version_articulo (articulo_id, texto, vigente_desde, content_hash) SELECT a.id, 'Los principios de libertad, capacidad y solidaridad económica informan todo el ordenamiento jurídico tributario.', '2003-12-17', '0f6150090fa2501c2f371f54c9882201' FROM articulo a JOIN norma n ON n.id = a.norma_id WHERE n.codigo = 'LGT' AND a.numero = '1';
INSERT INTO version_articulo (articulo_id, texto, vigente_desde, content_hash) SELECT a.id, 'La actuación de la Administración tributaria se regirá por los principios de eficacia, proporcionalidad, celeridad e imparcialidad.', '2003-12-17', '17ceac5561290ef648a3bd78355620c0' FROM articulo a JOIN norma n ON n.id = a.norma_id WHERE n.codigo = 'LGT' AND a.numero = '2';
INSERT INTO version_articulo (articulo_id, texto, vigente_desde, content_hash) SELECT a.id, 'Las normas tributarias se interpretarán de acuerdo con las reglas establecidas en los artículos 3 y 4 del Código Civil.', '2003-12-17', 'ae956c4e7021c0cd186aa41052ce66a7' FROM articulo a JOIN norma n ON n.id = a.norma_id WHERE n.codigo = 'LGT' AND a.numero = '3';
INSERT INTO version_articulo (articulo_id, texto, vigente_desde, content_hash) SELECT a.id, 'Las obligaciones tributarias principales y accesorias se establecen en esta ley y en las normas tributarias especiales.', '2003-12-17', '45473e14e03ef7e7d5f9ac727d0794d6' FROM articulo a JOIN norma n ON n.id = a.norma_id WHERE n.codigo = 'LGT' AND a.numero = '5';
INSERT INTO version_articulo (articulo_id, texto, vigente_desde, content_hash) SELECT a.id, 'Los sujetos pasivos son quienes realizan los hechos imponibles previstos en las normas tributarias.', '2003-12-17', 'ec30e8f63330546ecfe36d3876e6f6a5' FROM articulo a JOIN norma n ON n.id = a.norma_id WHERE n.codigo = 'LGT' AND a.numero = '10';
INSERT INTO version_articulo (articulo_id, texto, vigente_desde, content_hash) SELECT a.id, 'El hecho imponible es la conducta descrita por la norma tributaria como presupuesto del tributo.', '2003-12-17', 'dd1a191deb3dc9f4787d07530157947b' FROM articulo a JOIN norma n ON n.id = a.norma_id WHERE n.codigo = 'LGT' AND a.numero = '12';
INSERT INTO version_articulo (articulo_id, texto, vigente_desde, content_hash) SELECT a.id, 'La liquidación tributaria es el acto mediante el cual se determina la deuda tributaria.', '2003-12-17', 'ba1cd4aabe3a3d94cc986f27cab04d42' FROM articulo a JOIN norma n ON n.id = a.norma_id WHERE n.codigo = 'LGT' AND a.numero = '17';
INSERT INTO version_articulo (articulo_id, texto, vigente_desde, content_hash) SELECT a.id, 'Los derechos de la Administración para determinar las deudas tributarias prescriben en cuatro años.', '2003-12-17', '8f82abe7fa5eda91569eb9f10c3a2515' FROM articulo a JOIN norma n ON n.id = a.norma_id WHERE n.codigo = 'LGT' AND a.numero = '21';
INSERT INTO version_articulo (articulo_id, texto, vigente_desde, content_hash) SELECT a.id, 'Las infracciones tributarias serán sancionadas conforme a lo dispuesto en esta ley.', '2003-12-17', '6c60b9e61ac2f850c82887733f38c337' FROM articulo a JOIN norma n ON n.id = a.norma_id WHERE n.codigo = 'LGT' AND a.numero = '26';
INSERT INTO version_articulo (articulo_id, texto, vigente_desde, content_hash) SELECT a.id, 'Responderán del pago de las deudas tributarias los terceros previstos en esta ley.', '2003-12-17', '49c3b8c9f79b75ca6aa52cd55f0bdb4c' FROM articulo a JOIN norma n ON n.id = a.norma_id WHERE n.codigo = 'LGT' AND a.numero = '30';
INSERT INTO version_articulo (articulo_id, texto, vigente_desde, content_hash) SELECT a.id, 'Los residentes fiscales en España tributarán por sus rentas mundiales. Los no residentes tributarán solo por rentas obtenidas en España.', '2006-12-28', 'ec3f3c933968d605fcd843a6b67db0af' FROM articulo a JOIN norma n ON n.id = a.norma_id WHERE n.codigo = 'LIRPF' AND a.numero = '1';
INSERT INTO version_articulo (articulo_id, texto, vigente_desde, content_hash) SELECT a.id, 'Son sujetos pasivos los residentes y no residentes que obtengan rentas en territorio español.', '2006-12-28', '261b29f2bdf9f4e81e6d23e74671e65c' FROM articulo a JOIN norma n ON n.id = a.norma_id WHERE n.codigo = 'LIRPF' AND a.numero = '2';
INSERT INTO version_articulo (articulo_id, texto, vigente_desde, content_hash) SELECT a.id, 'Son rendimientos del trabajo las contraprestaciones obtenidas por servicios laborales por cuenta ajena.', '2006-12-28', '6211ad75600c09685d79a42209217623' FROM articulo a JOIN norma n ON n.id = a.norma_id WHERE n.codigo = 'LIRPF' AND a.numero = '3';
INSERT INTO version_articulo (articulo_id, texto, vigente_desde, content_hash) SELECT a.id, 'Son rendimientos de actividades económicas los obtenidos por el ejercicio directo, profesional o empresarial.', '2006-12-28', '1ca9472bf2cb14eed9b2149be121fdbf' FROM articulo a JOIN norma n ON n.id = a.norma_id WHERE n.codigo = 'LIRPF' AND a.numero = '4';
INSERT INTO version_articulo (articulo_id, texto, vigente_desde, content_hash) SELECT a.id, 'Son rendimientos del capital mobiliario los obtenidos por participaciones en entidades y créditos.', '2006-12-28', 'd64534740442b0a6f8d0cc56b31136a7' FROM articulo a JOIN norma n ON n.id = a.norma_id WHERE n.codigo = 'LIRPF' AND a.numero = '5';
INSERT INTO version_articulo (articulo_id, texto, vigente_desde, content_hash) SELECT a.id, 'Son ganancias patrimoniales el aumento o disminución del patrimonio obtenido por transmisión o no.', '2006-12-28', 'e424a70cb7f89d3dffcf001a9760a9c6' FROM articulo a JOIN norma n ON n.id = a.norma_id WHERE n.codigo = 'LIRPF' AND a.numero = '6';
INSERT INTO version_articulo (articulo_id, texto, vigente_desde, content_hash) SELECT a.id, 'Las deducciones en la cuota se aplicarán sobre el resultado de la declaración.', '2006-12-28', '2b2bed9a6e41c0ac097107d860dad662' FROM articulo a JOIN norma n ON n.id = a.norma_id WHERE n.codigo = 'LIRPF' AND a.numero = '8';
INSERT INTO version_articulo (articulo_id, texto, vigente_desde, content_hash) SELECT a.id, 'Las retenciones e ingresos a cuenta se practicarán sobre los rendimientos previstos en esta ley.', '2006-12-28', '8b0cd05720578113703c76aae8a17f4f' FROM articulo a JOIN norma n ON n.id = a.norma_id WHERE n.codigo = 'LIRPF' AND a.numero = '10';
INSERT INTO version_articulo (articulo_id, texto, vigente_desde, content_hash) SELECT a.id, 'Los contribuyentes que obtengan rendimientos del trabajo sujetos a retención presentarán declaración anual.', '2006-12-28', 'f51de9b6dd7513f174e3663a6ec9f4b8' FROM articulo a JOIN norma n ON n.id = a.norma_id WHERE n.codigo = 'LIRPF' AND a.numero = '16';
INSERT INTO version_articulo (articulo_id, texto, vigente_desde, content_hash) SELECT a.id, 'Los contribuyentes que ejerzan actividades económicas realizarán pagos fraccionados trimestrales.', '2006-12-28', 'ae94606b708ffb040fc170e85b26105f' FROM articulo a JOIN norma n ON n.id = a.norma_id WHERE n.codigo = 'LIRPF' AND a.numero = '19';
INSERT INTO version_articulo (articulo_id, texto, vigente_desde, content_hash) SELECT a.id, 'El hecho imponible del IVA consiste en la entrega de bienes y prestación de servicios en territorio español.', '1992-12-28', '5b4d385c41ab1d7d07c6c6fed9b477b0' FROM articulo a JOIN norma n ON n.id = a.norma_id WHERE n.codigo = 'LIVA' AND a.numero = '1';
INSERT INTO version_articulo (articulo_id, texto, vigente_desde, content_hash) SELECT a.id, 'Son sujetos pasivos los empresarios o profesionales que realicen entregas o prestaciones.', '1992-12-28', '91b43ae7bfe27c1240c6b6e07f51e612' FROM articulo a JOIN norma n ON n.id = a.norma_id WHERE n.codigo = 'LIVA' AND a.numero = '2';
INSERT INTO version_articulo (articulo_id, texto, vigente_desde, content_hash) SELECT a.id, 'Se entiende por bienes todas las cosas corporales y por servicios todas las prestaciones.', '1992-12-28', 'c2fecfe028025b07243d338c2c3904db' FROM articulo a JOIN norma n ON n.id = a.norma_id WHERE n.codigo = 'LIVA' AND a.numero = '3';
INSERT INTO version_articulo (articulo_id, texto, vigente_desde, content_hash) SELECT a.id, 'No estarán sujetas al IVA las entregas de bienes y prestaciones de servicios exentas.', '1992-12-28', '7f3eaf6c5bba6814b8775063ff930ecd' FROM articulo a JOIN norma n ON n.id = a.norma_id WHERE n.codigo = 'LIVA' AND a.numero = '6';
INSERT INTO version_articulo (articulo_id, texto, vigente_desde, content_hash) SELECT a.id, 'El tipo de gravamen general será del 21%. Podrán establecerse tipos reducidos.', '1992-12-28', '93a85326d72e630b80d16244ef1426ad' FROM articulo a JOIN norma n ON n.id = a.norma_id WHERE n.codigo = 'LIVA' AND a.numero = '8';
INSERT INTO version_articulo (articulo_id, texto, vigente_desde, content_hash) SELECT a.id, 'La cuota soportada es la IVA repercutida por el transmitente o prestador.', '1992-12-28', 'd434bde80973fa34a94090918bae5d6c' FROM articulo a JOIN norma n ON n.id = a.norma_id WHERE n.codigo = 'LIVA' AND a.numero = '10';
INSERT INTO version_articulo (articulo_id, texto, vigente_desde, content_hash) SELECT a.id, 'Los sujetos pasivos practicarán autoliquidaciones trimestrales o mensuales.', '1992-12-28', '7d624dcd9f9fab491d7da1f5ed861645' FROM articulo a JOIN norma n ON n.id = a.norma_id WHERE n.codigo = 'LIVA' AND a.numero = '12';
INSERT INTO version_articulo (articulo_id, texto, vigente_desde, content_hash) SELECT a.id, 'Las entregas de bienes y prestaciones de servicios se documentarán mediante facturas.', '1992-12-28', 'cd007be5c656966b6ebf512232307f31' FROM articulo a JOIN norma n ON n.id = a.norma_id WHERE n.codigo = 'LIVA' AND a.numero = '15';

-- 4. documento_interpretativo — circulares y resoluciones VAT/IRPF
INSERT INTO documento_interpretativo (referencia, tipo_documento, organismo_emisor, jurisdiccion, tipo_fuente, ambito, fecha, titulo, texto, url_fuente, numero_circular, referencia_boe, estado_vigencia, ambito_tematico, regulacion_relacionada, content_hash) VALUES ('VAT-2024-001', 'circular', 'AEAT', 'España', 'tributario', 'general', '2024-06-15', 'Interpretación IVA digital services', 'Las prestaciones de servicios electrónicos a consumidores finales se consideran realizadas en el país de destino del consumidor a partir de 2024.', 'https://sede.agenciatributaria.gob.es/Sede/ayuda/circulares/index.shtml', NULL, 'BOE-A-2024-11001', 'vigente', 'digital', 'Directiva 2006/112/CE', '842182ec0cc167c43835274d92887d67');
INSERT INTO documento_interpretativo (referencia, tipo_documento, organismo_emisor, jurisdiccion, tipo_fuente, ambito, fecha, titulo, texto, url_fuente, numero_circular, referencia_boe, estado_vigencia, ambito_tematico, regulacion_relacionada, content_hash) VALUES ('VAT-2024-002', 'resolucion', 'AEAT', 'España', 'tributario', 'general', '2024-09-20', 'Facturación electrónica obligatoria', 'A partir de 2024, las empresas obligadas a llevar el Libro Registro de Facturas emitidas deberán hacerlo en formato electrónico.', 'https://sede.agenciatributaria.gob.es/Sede/ayuda/resoluciones/index.shtml', NULL, 'BOE-A-2024-15002', 'vigente', 'facturacion', 'Ley 18/2022', 'ab567f557616f9280a142090c5886fd0');
INSERT INTO documento_interpretativo (referencia, tipo_documento, organismo_emisor, jurisdiccion, tipo_fuente, ambito, fecha, titulo, texto, url_fuente, numero_circular, referencia_boe, estado_vigencia, ambito_tematico, regulacion_relacionada, content_hash) VALUES ('IRPF-2024-001', 'circular', 'AEAT', 'España', 'tributario', 'general', '2024-03-10', 'Deducciones vivienda habitual 2024', 'Se actualizan los criterios de deducción por vivienda habitual para el ejercicio 2024, manteniendo el régimen transitorio.', 'https://sede.agenciatributaria.gob.es/Sede/ayuda/circulares/index.shtml', NULL, 'BOE-A-2024-05001', 'vigente', 'vivienda', 'LIRPF art. 68', 'b065aab02e0ee777263edace7d4487ad');
INSERT INTO documento_interpretativo (referencia, tipo_documento, organismo_emisor, jurisdiccion, tipo_fuente, ambito, fecha, titulo, texto, url_fuente, numero_circular, referencia_boe, estado_vigencia, ambito_tematico, regulacion_relacionada, content_hash) VALUES ('IRPF-2024-002', 'resolucion', 'AEAT', 'España', 'tributario', 'general', '2024-04-01', 'Retenciones autónomos 2024', 'Las retenciones para autónomos se calculan aplicando el tipo del 15% sobre la base estimada del ejercicio anterior.', 'https://sede.agenciatributaria.gob.es/Sede/ayuda/resoluciones/index.shtml', NULL, 'BOE-A-2024-05501', 'vigente', 'retenciones', 'LIRPF art. 92', '2b20cfa3e60d929a2ba6a271aeed5a9e');
INSERT INTO documento_interpretativo (referencia, tipo_documento, organismo_emisor, jurisdiccion, tipo_fuente, ambito, fecha, titulo, texto, url_fuente, numero_circular, referencia_boe, estado_vigencia, ambito_tematico, regulacion_relacionada, content_hash) VALUES ('LIS-2024-001', 'circular', 'AEAT', 'España', 'tributario', 'general', '2024-07-15', 'Deducción I+D+i 2024', 'La deducción por actividades de I+D+i se mantiene en un 42% para la parte fija y 14% para la variable en 2024.', 'https://sede.agenciatributaria.gob.es/Sede/ayuda/circulares/index.shtml', NULL, 'BOE-A-2024-12001', 'vigente', 'i+d', 'LIS art. 36', 'f490b50b613e9c82192ca929d570a541');

-- 5. documento_version — versiones de documentos interpretativos
INSERT INTO documento_version (documento_referencia, version_num, texto, cambio_tipo, fecha_version, url_version) VALUES ('VAT-2024-001', 1, (SELECT texto FROM documento_interpretativo d WHERE d.referencia = 'VAT-2024-001'), 'creacion', '2024-01-01', 'https://sede.agenciatributaria.gob.es');
INSERT INTO documento_version (documento_referencia, version_num, texto, cambio_tipo, fecha_version, url_version) VALUES ('VAT-2024-002', 1, (SELECT texto FROM documento_interpretativo d WHERE d.referencia = 'VAT-2024-002'), 'creacion', '2024-01-01', 'https://sede.agenciatributaria.gob.es');
INSERT INTO documento_version (documento_referencia, version_num, texto, cambio_tipo, fecha_version, url_version) VALUES ('IRPF-2024-001', 1, (SELECT texto FROM documento_interpretativo d WHERE d.referencia = 'IRPF-2024-001'), 'creacion', '2024-01-01', 'https://sede.agenciatributaria.gob.es');
INSERT INTO documento_version (documento_referencia, version_num, texto, cambio_tipo, fecha_version, url_version) VALUES ('IRPF-2024-002', 1, (SELECT texto FROM documento_interpretativo d WHERE d.referencia = 'IRPF-2024-002'), 'creacion', '2024-01-01', 'https://sede.agenciatributaria.gob.es');
INSERT INTO documento_version (documento_referencia, version_num, texto, cambio_tipo, fecha_version, url_version) VALUES ('LIS-2024-001', 1, (SELECT texto FROM documento_interpretativo d WHERE d.referencia = 'LIS-2024-001'), 'creacion', '2024-01-01', 'https://sede.agenciatributaria.gob.es');

-- 6. documento_fragmento — fragmentos de documentos
INSERT INTO documento_fragmento (documento_origen_tipo, documento_origen_id, chunk_index, chunk_type, titulo, texto, char_start, char_end, token_count, content_hash) SELECT 'interpretativo', d.id, 1, 'natural', 'Hecho imponible', 'Las prestaciones de servicios electrónicos a consumidores finales se consideran realizadas en el país de destino del consumidor.', 0, 120, 18, '3a5208b62d549efe12c56a373c7f6bdc' FROM documento_interpretativo d WHERE d.referencia = 'VAT-2024-001';
INSERT INTO documento_fragmento (documento_origen_tipo, documento_origen_id, chunk_index, chunk_type, titulo, texto, char_start, char_end, token_count, content_hash) SELECT 'interpretativo', d.id, 2, 'natural', 'Territorio de destino', 'A efectos del IVA digital, el consumidor se considera ubicado en el Estado miembro donde esté establecido.', 120, 240, 17, '3e756ed76e95254a0292e2662cb04863' FROM documento_interpretativo d WHERE d.referencia = 'VAT-2024-001';
INSERT INTO documento_fragmento (documento_origen_tipo, documento_origen_id, chunk_index, chunk_type, titulo, texto, char_start, char_end, token_count, content_hash) SELECT 'interpretativo', d.id, 1, 'natural', 'Obligación facturación electrónica', 'Las empresas obligadas a llevar el Libro Registro de Facturas deberán hacerlo en formato electrónico.', 0, 110, 16, 'ab241a8e03e086c724d49bc50a1bb86b' FROM documento_interpretativo d WHERE d.referencia = 'VAT-2024-002';
INSERT INTO documento_fragmento (documento_origen_tipo, documento_origen_id, chunk_index, chunk_type, titulo, texto, char_start, char_end, token_count, content_hash) SELECT 'interpretativo', d.id, 1, 'natural', 'Deducción vivienda', 'Se actualizan los criterios de deducción por vivienda habitual manteniendo el régimen transitorio.', 0, 100, 14, 'ff5e98208de4b9c98a3509229ed8f5e6' FROM documento_interpretativo d WHERE d.referencia = 'IRPF-2024-001';
INSERT INTO documento_fragmento (documento_origen_tipo, documento_origen_id, chunk_index, chunk_type, titulo, texto, char_start, char_end, token_count, content_hash) SELECT 'interpretativo', d.id, 1, 'natural', 'Retenciones autónomos', 'Las retenciones para autónomos se calculan aplicando el tipo del 15% sobre la base estimada.', 0, 95, 13, 'b0cf8130b1f656bde7427f691be6aa40' FROM documento_interpretativo d WHERE d.referencia = 'IRPF-2024-002';
INSERT INTO documento_fragmento (documento_origen_tipo, documento_origen_id, chunk_index, chunk_type, titulo, texto, char_start, char_end, token_count, content_hash) SELECT 'interpretativo', d.id, 1, 'natural', 'Deducción I+D', 'La deducción por actividades de I+D+i se mantiene en un 42% para la parte fija y 14% para la variable.', 0, 110, 16, 'ec6df2d5254bf8e7374fa938a74f0074' FROM documento_interpretativo d WHERE d.referencia = 'LIS-2024-001';

-- 7. documento_seccion — secciones de documentos
INSERT INTO documento_seccion (documento_origen_tipo, documento_origen_id, tipo_seccion, numero, titulo, nivel, orden) SELECT 'VAT-2024-001', d.id, 'interpretativo', '1', 'Introducción', 1, 1 FROM documento_interpretativo d WHERE d.referencia = 'interpretativo';
INSERT INTO documento_seccion (documento_origen_tipo, documento_origen_id, tipo_seccion, numero, titulo, nivel, orden) SELECT 'VAT-2024-001', d.id, 'interpretativo', '2', 'Servicios electrónicos', 2, 2 FROM documento_interpretativo d WHERE d.referencia = 'interpretativo';
INSERT INTO documento_seccion (documento_origen_tipo, documento_origen_id, tipo_seccion, numero, titulo, nivel, orden) SELECT 'VAT-2024-002', d.id, 'interpretativo', '1', 'Introducción', 1, 1 FROM documento_interpretativo d WHERE d.referencia = 'interpretativo';
INSERT INTO documento_seccion (documento_origen_tipo, documento_origen_id, tipo_seccion, numero, titulo, nivel, orden) SELECT 'VAT-2024-002', d.id, 'interpretativo', '2', 'Factura electrónica', 2, 2 FROM documento_interpretativo d WHERE d.referencia = 'interpretativo';
INSERT INTO documento_seccion (documento_origen_tipo, documento_origen_id, tipo_seccion, numero, titulo, nivel, orden) SELECT 'IRPF-2024-001', d.id, 'interpretativo', '1', 'Introducción', 1, 1 FROM documento_interpretativo d WHERE d.referencia = 'interpretativo';
INSERT INTO documento_seccion (documento_origen_tipo, documento_origen_id, tipo_seccion, numero, titulo, nivel, orden) SELECT 'IRPF-2024-001', d.id, 'interpretativo', '2', 'Vivienda habitual', 2, 2 FROM documento_interpretativo d WHERE d.referencia = 'interpretativo';
INSERT INTO documento_seccion (documento_origen_tipo, documento_origen_id, tipo_seccion, numero, titulo, nivel, orden) SELECT 'IRPF-2024-002', d.id, 'interpretativo', '1', 'Introducción', 1, 1 FROM documento_interpretativo d WHERE d.referencia = 'interpretativo';
INSERT INTO documento_seccion (documento_origen_tipo, documento_origen_id, tipo_seccion, numero, titulo, nivel, orden) SELECT 'IRPF-2024-002', d.id, 'interpretativo', '2', 'Autónomos', 2, 2 FROM documento_interpretativo d WHERE d.referencia = 'interpretativo';
INSERT INTO documento_seccion (documento_origen_tipo, documento_origen_id, tipo_seccion, numero, titulo, nivel, orden) SELECT 'LIS-2024-001', d.id, 'interpretativo', '1', 'Introducción', 1, 1 FROM documento_interpretativo d WHERE d.referencia = 'interpretativo';
INSERT INTO documento_seccion (documento_origen_tipo, documento_origen_id, tipo_seccion, numero, titulo, nivel, orden) SELECT 'LIS-2024-001', d.id, 'interpretativo', '2', 'I+D+i', 2, 2 FROM documento_interpretativo d WHERE d.referencia = 'interpretativo';

-- 8. empresa — empresas de referencia
INSERT INTO empresa (nombre, nif, domicilio, fuente_inicial, content_hash) VALUES ('Telefónica, S.A.', 'A28012345', 'Madrid, España', 'registro_mercantil', 'dbf047ecb85fb17c3ed9893d7e180398');
INSERT INTO empresa (nombre, nif, domicilio, fuente_inicial, content_hash) VALUES ('Inditex, S.A.', 'A15098765', 'A Coruña, España', 'registro_mercantil', 'eb61893ff6fea9bbf25ba8d921783491');
INSERT INTO empresa (nombre, nif, domicilio, fuente_inicial, content_hash) VALUES ('Banco Santander, S.A.', 'A30012345', 'Santander, España', 'registro_mercantil', '78fa10ca976b3a38d436dd763dd3ef4a');
INSERT INTO empresa (nombre, nif, domicilio, fuente_inicial, content_hash) VALUES ('Iberdrola, S.A.', 'A48012345', 'Bilbao, España', 'registro_mercantil', 'e70e770172c2f286483f21874e0373c3');
INSERT INTO empresa (nombre, nif, domicilio, fuente_inicial, content_hash) VALUES ('Mapfre, S.A.', 'A28098765', 'Madrid, España', 'registro_mercantil', '8e5968b06c1e4e00b0a5d7510cecf7d3');

-- 9. documento_empresa — vínculos empresa-documento
INSERT INTO documento_empresa (documento_id, empresa_id, rol, confianza_extraccion, nota) SELECT d.id, e.id, 'contribuyente', 0.95, 'Empresa obligada a facturación electrónica' FROM documento_interpretativo d, empresa e WHERE d.referencia = 'VAT-2024-002' AND e.id = 1;
INSERT INTO documento_empresa (documento_id, empresa_id, rol, confianza_extraccion, nota) SELECT d.id, e.id, 'contribuyente', 0.95, 'Empresa obligada a facturación electrónica' FROM documento_interpretativo d, empresa e WHERE d.referencia = 'VAT-2024-002' AND e.id = 2;
INSERT INTO documento_empresa (documento_id, empresa_id, rol, confianza_extraccion, nota) SELECT d.id, e.id, 'contribuyente', 0.9, 'Entidad financiera sujeta a obligaciones' FROM documento_interpretativo d, empresa e WHERE d.referencia = 'VAT-2024-002' AND e.id = 3;
INSERT INTO documento_empresa (documento_id, empresa_id, rol, confianza_extraccion, nota) SELECT d.id, e.id, 'contribuyente', 0.9, 'Empresa con empleados con derecho a deducción' FROM documento_interpretativo d, empresa e WHERE d.referencia = 'IRPF-2024-001' AND e.id = 1;
INSERT INTO documento_empresa (documento_id, empresa_id, rol, confianza_extraccion, nota) SELECT d.id, e.id, 'contribuyente', 0.95, 'Empresa con autónomos como empleados' FROM documento_interpretativo d, empresa e WHERE d.referencia = 'IRPF-2024-002' AND e.id = 1;
INSERT INTO documento_empresa (documento_id, empresa_id, rol, confianza_extraccion, nota) SELECT d.id, e.id, 'contribuyente', 0.95, 'Empresa con actividades I+D' FROM documento_interpretativo d, empresa e WHERE d.referencia = 'LIS-2024-001' AND e.id = 1;
INSERT INTO documento_empresa (documento_id, empresa_id, rol, confianza_extraccion, nota) SELECT d.id, e.id, 'contribuyente', 0.95, 'Empresa con actividades I+D' FROM documento_interpretativo d, empresa e WHERE d.referencia = 'LIS-2024-001' AND e.id = 2;

-- 10. obligacion_regulatoria — obligaciones regulatorias
INSERT INTO obligacion_regulatoria (codigo, nombre, fuente, organismo_emisor, tipo_obligacion, sujeto_obligado, periodicidad, reporte_modelo, ambito, estado_vigencia, documento_origen_tipo, documento_origen_ref, seccion_origen, anexo_origen, nota, plazo_dias, frecuencia_presentacion, ventana_presentacion, trigger_presentacion, canal_presentacion, obligados_resumen, sancion_min, sancion_max, recargo_voluntario, recargo_involuntario, interes_demora, prescripcion_anos, deposito_previo, fuentes_operativas, ultima_actualizacion, origen_metadato, estado_metadato) VALUES ('OBL-IRPF-100', 'Presentar modelo 100 — IRPF anual', 'AEAT', 'Agencia Estatal de Administración Tributaria', 'declaracion', 'contribuyente_irpf', 'anual', '100', 'general', 'vigente', 'interpretativo', 'IRPF-2024-001', 'Sección 1', NULL, 'Obligación de presentar declaración anual del IRPF para contribuyentes con rentas superiores a umbral legal.', '90', 'trimestral', 'del 1 al 20 de abril, julio, octubre y enero', 'evento_calendario', 'electronica', ' contribuyentes IRPF obligados a declarar ', '500', '6000000', 'voluntario', 'involuntario', 'demora', '4', 'no', '{"tipo": "modelo", "version": "2025", "canal": "electronico"}', '2024-12-20', 'seed_curado', 'curado');
INSERT INTO obligacion_regulatoria (codigo, nombre, fuente, organismo_emisor, tipo_obligacion, sujeto_obligado, periodicidad, reporte_modelo, ambito, estado_vigencia, documento_origen_tipo, documento_origen_ref, seccion_origen, anexo_origen, nota, plazo_dias, frecuencia_presentacion, ventana_presentacion, trigger_presentacion, canal_presentacion, obligados_resumen, sancion_min, sancion_max, recargo_voluntario, recargo_involuntario, interes_demora, prescripcion_anos, deposito_previo, fuentes_operativas, ultima_actualizacion, origen_metadato, estado_metadato) VALUES ('OBL-IVA-303', 'Presentar modelo 303 — IVA trimestral', 'AEAT', 'Agencia Estatal de Administración Tributaria', 'declaracion', 'empresario_iva', 'trimestral', '303', 'general', 'vigente', 'interpretativo', 'VAT-2024-001', 'Sección 1', NULL, 'Obligación de autoliquidar IVA trimestralmente.', '90', 'trimestral', 'del 1 al 20 de abril, julio, octubre y enero', 'evento_calendario', 'electronica', ' empresarios y profesionales sujetos a IVA ', '500', '6000000', 'voluntario', 'involuntario', 'demora', '4', 'no', '{"tipo": "modelo", "version": "2025", "canal": "electronico"}', '2024-12-20', 'seed_curado', 'curado');
INSERT INTO obligacion_regulatoria (codigo, nombre, fuente, organismo_emisor, tipo_obligacion, sujeto_obligado, periodicidad, reporte_modelo, ambito, estado_vigencia, documento_origen_tipo, documento_origen_ref, seccion_origen, anexo_origen, nota, plazo_dias, frecuencia_presentacion, ventana_presentacion, trigger_presentacion, canal_presentacion, obligados_resumen, sancion_min, sancion_max, recargo_voluntario, recargo_involuntario, interes_demora, prescripcion_anos, deposito_previo, fuentes_operativas, ultima_actualizacion, origen_metadato, estado_metadato) VALUES ('OBL-IVA-390', 'Presentar modelo 390 — IVA anual', 'AEAT', 'Agencia Estatal de Administración Tributaria', 'declaracion', 'empresario_iva', 'anual', '390', 'general', 'vigente', 'interpretativo', 'VAT-2024-001', 'Sección 2', NULL, 'Obligación de presentar resumen anual del IVA.', '90', 'anual', 'enero del año siguiente', 'evento_calendario', 'electronica', ' empresarios y profesionales sujetos a IVA ', '500', '6000000', 'voluntario', 'involuntario', 'demora', '4', 'no', '{"tipo": "modelo", "version": "2025", "canal": "electronico"}', '2024-12-20', 'seed_curado', 'curado');
INSERT INTO obligacion_regulatoria (codigo, nombre, fuente, organismo_emisor, tipo_obligacion, sujeto_obligado, periodicidad, reporte_modelo, ambito, estado_vigencia, documento_origen_tipo, documento_origen_ref, seccion_origen, anexo_origen, nota, plazo_dias, frecuencia_presentacion, ventana_presentacion, trigger_presentacion, canal_presentacion, obligados_resumen, sancion_min, sancion_max, recargo_voluntario, recargo_involuntario, interes_demora, prescripcion_anos, deposito_previo, fuentes_operativas, ultima_actualizacion, origen_metadato, estado_metadato) VALUES ('OBL-FACT-001', 'Facturación electrónica', 'AEAT', 'Agencia Estatal de Administración Tributaria', 'registro', 'empresario_iva', 'continua', NULL, 'general', 'vigente', 'interpretativo', 'VAT-2024-002', 'Sección 1', NULL, 'Obligación de llevar libros registro de facturación en formato electrónico.', NULL, NULL, 'continua', 'evento_sistema', 'electronica', ' empresas obligadas a LRF ', NULL, NULL, NULL, NULL, NULL, '4', 'no', '{"tipo": "libro", "version": "electronic", "canal": "siae"}', '2024-12-20', 'seed_curado', 'curado');
INSERT INTO obligacion_regulatoria (codigo, nombre, fuente, organismo_emisor, tipo_obligacion, sujeto_obligado, periodicidad, reporte_modelo, ambito, estado_vigencia, documento_origen_tipo, documento_origen_ref, seccion_origen, anexo_origen, nota, plazo_dias, frecuencia_presentacion, ventana_presentacion, trigger_presentacion, canal_presentacion, obligados_resumen, sancion_min, sancion_max, recargo_voluntario, recargo_involuntario, interes_demora, prescripcion_anos, deposito_previo, fuentes_operativas, ultima_actualizacion, origen_metadato, estado_metadato) VALUES ('OBL-347', 'Presentar modelo 347 — Operaciones con terceros', 'AEAT', 'Agencia Estatal de Administración Tributaria', 'declaracion', 'declarante', 'anual', '347', 'general', 'vigente', 'interpretativo', 'VAT-2024-001', 'Sección 3', NULL, 'Obligación de declarar operaciones con terceros superiores a umbral.', '90', 'anual', 'febrero del año siguiente', 'evento_calendario', 'electronica', ' empresarios y profesionales con operaciones > 3005,06€ ', '500', '6000000', 'voluntario', 'involuntario', 'demora', '4', 'no', '{"tipo": "modelo", "version": "2025", "canal": "electronico"}', '2024-12-20', 'seed_curado', 'curado');
INSERT INTO obligacion_regulatoria (codigo, nombre, fuente, organismo_emisor, tipo_obligacion, sujeto_obligado, periodicidad, reporte_modelo, ambito, estado_vigencia, documento_origen_tipo, documento_origen_ref, seccion_origen, anexo_origen, nota, plazo_dias, frecuencia_presentacion, ventana_presentacion, trigger_presentacion, canal_presentacion, obligados_resumen, sancion_min, sancion_max, recargo_voluntario, recargo_involuntario, interes_demora, prescripcion_anos, deposito_previo, fuentes_operativas, ultima_actualizacion, origen_metadato, estado_metadato) VALUES ('OBL-IRNR-124', 'Presentar modelo 124 — IRNR retenciones', 'AEAT', 'Agencia Estatal de Administración Tributaria', 'declaracion', 'retenedor_irnr', 'mensual', '124', 'irnr', 'vigente', 'interpretativo', 'IRPF-2024-002', 'Sección 2', NULL, 'Obligación de declarar retenciones a no residentes.', '90', 'mensual', 'primeros 20 días del mes siguiente', 'evento_calendario', 'electronica', ' retenedores de rentas a no residentes ', '500', '6000000', 'voluntario', 'involuntario', 'demora', '4', 'no', '{"tipo": "modelo", "version": "2025", "canal": "electronico"}', '2024-12-20', 'seed_curado', 'curado');

-- 11. micro_obligacion — micro-obligaciones desglose
INSERT INTO micro_obligacion (codigo, nombre, descripcion, regulacion_relacionada, ambito, trigger_evento, frecuencia, owner_rol, severidad, activo) VALUES ('MO-IRPF-001', 'Verificar datos personales', 'Recopilar y verificar DNI, NIE y datos fiscales del contribuyente', 'LGT art. 10', 'tributario', 'evento_presentacion', 'anual', 'contribuyente', 'baja', True);
INSERT INTO micro_obligacion (codigo, nombre, descripcion, regulacion_relacionada, ambito, trigger_evento, frecuencia, owner_rol, severidad, activo) VALUES ('MO-IRPF-002', 'Calcular rendimientos del trabajo', 'Sumar todos los ingresos salariales del año', 'LIRPF art. 3', 'tributario', 'evento_calendario', 'anual', 'contribuyente', 'media', True);
INSERT INTO micro_obligacion (codigo, nombre, descripcion, regulacion_relacionada, ambito, trigger_evento, frecuencia, owner_rol, severidad, activo) VALUES ('MO-IRPF-003', 'Aplicar retenciones', 'Sumar retenciones practicadas por empleadores', 'LIRPF art. 10', 'tributario', 'evento_calendario', 'trimestral', 'retenedor', 'baja', True);
INSERT INTO micro_obligacion (codigo, nombre, descripcion, regulacion_relacionada, ambito, trigger_evento, frecuencia, owner_rol, severidad, activo) VALUES ('MO-IVA-001', 'Calcular cuota repercutida', 'Sumar IVA cobrado a clientes', 'LIVA art. 11', 'tributario', 'evento_calendario', 'trimestral', 'empresario', 'media', True);
INSERT INTO micro_obligacion (codigo, nombre, descripcion, regulacion_relacionada, ambito, trigger_evento, frecuencia, owner_rol, severidad, activo) VALUES ('MO-IVA-002', 'Calcular cuota soportada', 'Sumar IVA pagado a proveedores', 'LIVA art. 10', 'tributario', 'evento_calendario', 'trimestral', 'empresario', 'media', True);
INSERT INTO micro_obligacion (codigo, nombre, descripcion, regulacion_relacionada, ambito, trigger_evento, frecuencia, owner_rol, severidad, activo) VALUES ('MO-IVA-003', 'Liquidar diferencia', 'Restar soportada de repercutida', 'LIVA art. 12', 'tributario', 'evento_calendario', 'trimestral', 'empresario', 'alta', True);
INSERT INTO micro_obligacion (codigo, nombre, descripcion, regulacion_relacionada, ambito, trigger_evento, frecuencia, owner_rol, severidad, activo) VALUES ('MO-FACT-001', 'Generar factura electrónica', 'Crear factura en formato XML/NFE', 'LIVA art. 15', 'tributario', 'evento_operacion', 'continua', 'empresario', 'media', True);
INSERT INTO micro_obligacion (codigo, nombre, descripcion, regulacion_relacionada, ambito, trigger_evento, frecuencia, owner_rol, severidad, activo) VALUES ('MO-FACT-002', 'Registrar factura emitida', 'Cargar factura en Libro Registro', 'LIVA art. 29', 'tributario', 'evento_operacion', 'continua', 'empresario', 'baja', True);
INSERT INTO micro_obligacion (codigo, nombre, descripcion, regulacion_relacionada, ambito, trigger_evento, frecuencia, owner_rol, severidad, activo) VALUES ('MO-347-001', 'Recopilar operaciones terceros', 'Agrupar operaciones por NIF de tercero', 'LGT art. 240', 'tributario', 'evento_calendario', 'anual', 'declarante', 'media', True);
INSERT INTO micro_obligacion (codigo, nombre, descripcion, regulacion_relacionada, ambito, trigger_evento, frecuencia, owner_rol, severidad, activo) VALUES ('MO-347-002', 'Verificar umbral 3005,06€', 'Comparar total anual por tercero con umbral', 'LGT art. 240', 'tributario', 'evento_calendario', 'anual', 'declarante', 'alta', True);

-- 12. obligacion_micro_obligacion — vinculación
INSERT INTO obligacion_micro_obligacion (obligacion_id, micro_obligacion_id, orden, evidencia_requerida) SELECT o.id, m.id, 1, 'registro_automatico' FROM obligacion_regulatoria o, micro_obligacion m WHERE o.codigo = 'OBL-IRPF-100' AND m.codigo = 'MO-IRPF-001';
INSERT INTO obligacion_micro_obligacion (obligacion_id, micro_obligacion_id, orden, evidencia_requerida) SELECT o.id, m.id, 2, 'registro_automatico' FROM obligacion_regulatoria o, micro_obligacion m WHERE o.codigo = 'OBL-IRPF-100' AND m.codigo = 'MO-IRPF-002';
INSERT INTO obligacion_micro_obligacion (obligacion_id, micro_obligacion_id, orden, evidencia_requerida) SELECT o.id, m.id, 3, 'registro_automatico' FROM obligacion_regulatoria o, micro_obligacion m WHERE o.codigo = 'OBL-IRPF-100' AND m.codigo = 'MO-IRPF-003';
INSERT INTO obligacion_micro_obligacion (obligacion_id, micro_obligacion_id, orden, evidencia_requerida) SELECT o.id, m.id, 1, 'registro_automatico' FROM obligacion_regulatoria o, micro_obligacion m WHERE o.codigo = 'OBL-IVA-303' AND m.codigo = 'MO-IVA-001';
INSERT INTO obligacion_micro_obligacion (obligacion_id, micro_obligacion_id, orden, evidencia_requerida) SELECT o.id, m.id, 2, 'registro_automatico' FROM obligacion_regulatoria o, micro_obligacion m WHERE o.codigo = 'OBL-IVA-303' AND m.codigo = 'MO-IVA-002';
INSERT INTO obligacion_micro_obligacion (obligacion_id, micro_obligacion_id, orden, evidencia_requerida) SELECT o.id, m.id, 3, 'registro_automatico' FROM obligacion_regulatoria o, micro_obligacion m WHERE o.codigo = 'OBL-IVA-303' AND m.codigo = 'MO-IVA-003';
INSERT INTO obligacion_micro_obligacion (obligacion_id, micro_obligacion_id, orden, evidencia_requerida) SELECT o.id, m.id, 1, 'registro_automatico' FROM obligacion_regulatoria o, micro_obligacion m WHERE o.codigo = 'OBL-FACT-001' AND m.codigo = 'MO-FACT-001';
INSERT INTO obligacion_micro_obligacion (obligacion_id, micro_obligacion_id, orden, evidencia_requerida) SELECT o.id, m.id, 2, 'registro_automatico' FROM obligacion_regulatoria o, micro_obligacion m WHERE o.codigo = 'OBL-FACT-001' AND m.codigo = 'MO-FACT-002';
INSERT INTO obligacion_micro_obligacion (obligacion_id, micro_obligacion_id, orden, evidencia_requerida) SELECT o.id, m.id, 1, 'registro_automatico' FROM obligacion_regulatoria o, micro_obligacion m WHERE o.codigo = 'OBL-347' AND m.codigo = 'MO-347-001';
INSERT INTO obligacion_micro_obligacion (obligacion_id, micro_obligacion_id, orden, evidencia_requerida) SELECT o.id, m.id, 2, 'registro_automatico' FROM obligacion_regulatoria o, micro_obligacion m WHERE o.codigo = 'OBL-347' AND m.codigo = 'MO-347-002';

-- 13. obligacion_documento — vínculos obligación-documento
INSERT INTO obligacion_documento (obligacion_id, documento_id, tipo_relacion) SELECT o.id, d.id, 'implementa' FROM obligacion_regulatoria o, documento_interpretativo d WHERE o.codigo = 'OBL-IRPF-100' AND d.referencia = 'IRPF-2024-001';
INSERT INTO obligacion_documento (obligacion_id, documento_id, tipo_relacion) SELECT o.id, d.id, 'implementa' FROM obligacion_regulatoria o, documento_interpretativo d WHERE o.codigo = 'OBL-IVA-303' AND d.referencia = 'VAT-2024-001';
INSERT INTO obligacion_documento (obligacion_id, documento_id, tipo_relacion) SELECT o.id, d.id, 'complementa' FROM obligacion_regulatoria o, documento_interpretativo d WHERE o.codigo = 'OBL-IVA-390' AND d.referencia = 'VAT-2024-001';
INSERT INTO obligacion_documento (obligacion_id, documento_id, tipo_relacion) SELECT o.id, d.id, 'implementa' FROM obligacion_regulatoria o, documento_interpretativo d WHERE o.codigo = 'OBL-FACT-001' AND d.referencia = 'VAT-2024-002';
INSERT INTO obligacion_documento (obligacion_id, documento_id, tipo_relacion) SELECT o.id, d.id, 'complementa' FROM obligacion_regulatoria o, documento_interpretativo d WHERE o.codigo = 'OBL-347' AND d.referencia = 'VAT-2024-001';
INSERT INTO obligacion_documento (obligacion_id, documento_id, tipo_relacion) SELECT o.id, d.id, 'implementa' FROM obligacion_regulatoria o, documento_interpretativo d WHERE o.codigo = 'OBL-IRNR-124' AND d.referencia = 'IRPF-2024-002';

-- 14. documento_articulo — vínculos documento-artículo
INSERT INTO documento_articulo (documento_id, articulo_id, metodo_enlace, confianza_enlace, nota) SELECT d.id, a.id, 'implementa', 0.95, 'Declaración anual IRPF' FROM documento_interpretativo d, articulo a, norma n WHERE d.referencia = 'IRPF-2024-001' AND a.norma_id = n.id AND n.codigo = 'LIRPF' AND a.numero = '16';
INSERT INTO documento_articulo (documento_id, articulo_id, metodo_enlace, confianza_enlace, nota) SELECT d.id, a.id, 'implementa', 0.9, 'Forma de presentación' FROM documento_interpretativo d, articulo a, norma n WHERE d.referencia = 'IRPF-2024-001' AND a.norma_id = n.id AND n.codigo = 'LIRPF' AND a.numero = '17';
INSERT INTO documento_articulo (documento_id, articulo_id, metodo_enlace, confianza_enlace, nota) SELECT d.id, a.id, 'interpreta', 0.92, 'Retenciones e ingresos a cuenta' FROM documento_interpretativo d, articulo a, norma n WHERE d.referencia = 'IRPF-2024-002' AND a.norma_id = n.id AND n.codigo = 'LIRPF' AND a.numero = '10';
INSERT INTO documento_articulo (documento_id, articulo_id, metodo_enlace, confianza_enlace, nota) SELECT d.id, a.id, 'interpreta', 0.88, 'Pagos fraccionados' FROM documento_interpretativo d, articulo a, norma n WHERE d.referencia = 'IRPF-2024-002' AND a.norma_id = n.id AND n.codigo = 'LIRPF' AND a.numero = '19';
INSERT INTO documento_articulo (documento_id, articulo_id, metodo_enlace, confianza_enlace, nota) SELECT d.id, a.id, 'interpreta', 0.95, 'Hecho imponible IVA' FROM documento_interpretativo d, articulo a, norma n WHERE d.referencia = 'VAT-2024-001' AND a.norma_id = n.id AND n.codigo = 'LIVA' AND a.numero = '1';
INSERT INTO documento_articulo (documento_id, articulo_id, metodo_enlace, confianza_enlace, nota) SELECT d.id, a.id, 'implementa', 0.9, 'Autoliquidaciones' FROM documento_interpretativo d, articulo a, norma n WHERE d.referencia = 'VAT-2024-001' AND a.norma_id = n.id AND n.codigo = 'LIVA' AND a.numero = '12';
INSERT INTO documento_articulo (documento_id, articulo_id, metodo_enlace, confianza_enlace, nota) SELECT d.id, a.id, 'implementa', 0.95, 'Facturación' FROM documento_interpretativo d, articulo a, norma n WHERE d.referencia = 'VAT-2024-002' AND a.norma_id = n.id AND n.codigo = 'LIVA' AND a.numero = '15';
INSERT INTO documento_articulo (documento_id, articulo_id, metodo_enlace, confianza_enlace, nota) SELECT d.id, a.id, 'interpreta', 0.9, 'Deducciones I+D' FROM documento_interpretativo d, articulo a, norma n WHERE d.referencia = 'LIS-2024-001' AND a.norma_id = n.id AND n.codigo = 'LIS' AND a.numero = '5';

-- 15. embedding_version — tracking de embeddings generados
INSERT INTO embedding_version (entity_table, entity_id, model_name, content_hash, dimensions, created_at) SELECT 'documento_interpretativo', d.id, 'esdata-text-embedding-3-small', 'a7667fd32391ae92a0a48592cc59a141', 256, '2024-12-20' FROM documento_interpretativo d WHERE d.referencia = 'VAT-2024-001';
INSERT INTO embedding_version (entity_table, entity_id, model_name, content_hash, dimensions, created_at) SELECT 'documento_interpretativo', d.id, 'esdata-text-embedding-3-small', 'b0992834d4fccb405b1ea0c49fa1d585', 256, '2024-12-20' FROM documento_interpretativo d WHERE d.referencia = 'VAT-2024-002';
INSERT INTO embedding_version (entity_table, entity_id, model_name, content_hash, dimensions, created_at) SELECT 'documento_interpretativo', d.id, 'esdata-text-embedding-3-small', 'ba93f8a5a6a82d8673d87312c5ec969a', 256, '2024-12-20' FROM documento_interpretativo d WHERE d.referencia = 'IRPF-2024-001';
INSERT INTO embedding_version (entity_table, entity_id, model_name, content_hash, dimensions, created_at) SELECT 'documento_interpretativo', d.id, 'esdata-text-embedding-3-small', '389e26919b8fc8ed7ff3e15a8f71ef80', 256, '2024-12-20' FROM documento_interpretativo d WHERE d.referencia = 'IRPF-2024-002';
INSERT INTO embedding_version (entity_table, entity_id, model_name, content_hash, dimensions, created_at) SELECT 'documento_interpretativo', d.id, 'esdata-text-embedding-3-small', '2089b4c4bfaabdd4e44644bbbddb6ecb', 256, '2024-12-20' FROM documento_interpretativo d WHERE d.referencia = 'LIS-2024-001';
INSERT INTO embedding_version (entity_table, entity_id, model_name, content_hash, dimensions, created_at) SELECT 'norma', n.id, 'esdata-text-embedding-3-small', 'ed6a3bdd92f68a5eb365b3a6a70dc483', 256, '2024-12-20' FROM norma n WHERE n.codigo = 'LGT';
INSERT INTO embedding_version (entity_table, entity_id, model_name, content_hash, dimensions, created_at) SELECT 'norma', n.id, 'esdata-text-embedding-3-small', 'e999fc5590a492f23679ffa1ef043a36', 256, '2024-12-20' FROM norma n WHERE n.codigo = 'LIRPF';
INSERT INTO embedding_version (entity_table, entity_id, model_name, content_hash, dimensions, created_at) SELECT 'norma', n.id, 'esdata-text-embedding-3-small', 'c5531c4c1e3b2b800789679f77c34984', 256, '2024-12-20' FROM norma n WHERE n.codigo = 'LIVA';
INSERT INTO embedding_version (entity_table, entity_id, model_name, content_hash, dimensions, created_at) SELECT 'norma', n.id, 'esdata-text-embedding-3-small', '3cf8ce107963d872a3f91259ace0f23b', 256, '2024-12-20' FROM norma n WHERE n.codigo = 'LIS';
INSERT INTO embedding_version (entity_table, entity_id, model_name, content_hash, dimensions, created_at) SELECT 'articulo', a.id, 'esdata-text-embedding-3-small', 'b078f69b5d32d65ea4c5f466a60a49a9', 256, '2024-12-20' FROM articulo a, norma n WHERE a.norma_id = n.id AND n.codigo = 'LGT' AND a.numero = '1';
INSERT INTO embedding_version (entity_table, entity_id, model_name, content_hash, dimensions, created_at) SELECT 'articulo', a.id, 'esdata-text-embedding-3-small', 'd651bfd8f61505235b6815f130673033', 256, '2024-12-20' FROM articulo a, norma n WHERE a.norma_id = n.id AND n.codigo = 'LIRPF' AND a.numero = '1';
INSERT INTO embedding_version (entity_table, entity_id, model_name, content_hash, dimensions, created_at) SELECT 'articulo', a.id, 'esdata-text-embedding-3-small', '83dfd468ed217328b64e4324cc0855f7', 256, '2024-12-20' FROM articulo a, norma n WHERE a.norma_id = n.id AND n.codigo = 'LIVA' AND a.numero = '1';
